# Generated by Django 4.2.11 on 2024-03-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0002_client_remove_company_is_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='deadline',
        ),
        migrations.AddField(
            model_name='client',
            name='client_contact',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='Active', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_tracker.company'),
        ),
    ]
