# Generated by Django 4.2.11 on 2024-03-15 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0008_project_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('member_email', models.EmailField(max_length=50)),
                ('member_role', models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee')], default='Employee', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_tracker.project')),
            ],
        ),
    ]
