# Generated by Django 4.2.11 on 2024-03-15 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0009_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_tracker.company'),
        ),
    ]
