# Generated by Django 4.2.11 on 2024-03-19 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0010_member_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_now', models.DateField()),
                ('time_spent', models.DurationField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_tracker.project')),
            ],
        ),
    ]
