# Generated by Django 4.2.11 on 2024-03-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0012_registerhours_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerhours',
            name='user',
        ),
    ]
