# Generated by Django 4.2.11 on 2024-03-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0014_registerhours_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerhours',
            name='member',
        ),
    ]
