# Generated by Django 4.2.11 on 2024-03-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0017_rename_date_now_registerhours_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerhours',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
