# Generated by Django 4.2.11 on 2024-03-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0018_alter_registerhours_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerhours',
            name='time_spent',
            field=models.CharField(max_length=20),
        ),
    ]
