# Generated by Django 4.2.11 on 2024-03-22 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0019_alter_registerhours_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerhours',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 7, 48, 8, 60428)),
        ),
    ]
