# Generated by Django 4.2.11 on 2024-03-22 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0020_alter_registerhours_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerhours',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 7, 49, 56, 454818)),
        ),
    ]
