# Generated by Django 4.2.11 on 2024-03-22 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0021_alter_registerhours_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_deadline',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 8, 15, 30, 474577)),
        ),
        migrations.AlterField(
            model_name='registerhours',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 8, 15, 30, 474992)),
        ),
    ]
