# Generated by Django 4.2.11 on 2024-03-25 06:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0023_alter_project_project_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project_tracker.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_deadline',
            field=models.DateField(default=datetime.datetime(2024, 3, 25, 6, 35, 9, 250457)),
        ),
        migrations.AlterField(
            model_name='registerhours',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 25, 6, 35, 9, 250954)),
        ),
    ]
